# Generated by Django 3.2.7 on 2021-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('distance', models.IntegerField(verbose_name='Distance')),
            ],
        ),
    ]
